version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: ~/project/build.sh
      - run: ~/project/publish.sh
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
